# Generated by Django 3.2.5 on 2023-02-02 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0002_auto_20211109_1456'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.bus')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BusShift',
                'verbose_name_plural': 'BusShifts',
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.DateTimeField(blank=True, default='', null=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geography.place')),
            ],
            options={
                'verbose_name': 'BusStop',
                'verbose_name_plural': 'BusStops',
            },
        ),
        migrations.CreateModel(
            name='BusStopInBusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default='')),
                ('date', models.DateTimeField(blank=True, default='', null=True)),
                ('bus_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bus_shift.busshift', verbose_name='Bus Stop')),
                ('bus_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bus_shift.busstop', verbose_name='Bus Stop')),
            ],
            options={
                'verbose_name': 'Bus Stop In Bus Shift',
                'verbose_name_plural': 'Bus Stops In Bus Shifts',
            },
        ),
        migrations.AddField(
            model_name='busshift',
            name='stop',
            field=models.ManyToManyField(to='bus_shift.BusStopInBusShift', verbose_name='stop'),
        ),
    ]
